"""empty message

Revision ID: 937bbd35945a
Revises: 
Create Date: 2020-04-13 00:43:25.019288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937bbd35945a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_managerDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_managerDB')
    # ### end Alembic commands ###
